### ISSUE TITLE
Clickable/editable Mouse Binding labels

### ISSUE THREAD

**Issue by hbaileylxd** [bright-tools/bwm#20]
It seems I can click in the labels under Mouse Bindings in Options and type in anything I want!

Can get it back to what it was by closing and restarting the program :)

![image](https://cloud.githubusercontent.com/assets/11558341/19694264/80e296b6-9ad6-11e6-8f88-eeb3b375c020.png)

**Comment by bright-tools** [comment]
Oh dear.  Editable attribute was left enabled!  Thanks for the report!
